### ISSUE TITLE
Minify without the last ";" of the class properties values

### ISSUE THREAD

**Issue by noloop** [noloop/cl-minify-css#1]
Example:

Instead it:

```css
body{padding:1em;margin:0 auto;max-width:33em;}@media (min-width:70em){body{font-size:130%;}}h1{font-size:1.5em;}
```

Minify thus:

```css
body{padding:1em;margin:0 auto;max-width:33em}@media (min-width:70em){body{font-size:130%}}h1{font-size:1.5em}
```
