### ISSUE TITLE
Minify without duplicated code

### ISSUE THREAD

**Issue by noloop** [noloop/cl-minify-css#2]
Example:

Instead it:

```css 
body{padding:1em;}body{padding:1em;}.some-class{padding:1em;}
```

Minify thus:

```css
body,.some-class{padding:1em;}
```
